version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

  timemanager:
    build:
      context: ./
    container_name: timemanager
    depends_on:
      - postgres
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
      
  vuejs:
    build:
      context: ./
      dockerfile: DockerfileVue
    container_name: vuejs
    working_dir: /app
    volumes:
      - ./vue:/app 
      - ./entrypointVue.sh:/app/entrypoint.sh
    ports:
      - "5173:5173"
